#!/usr/bin/env python3
"""Install this skill and its /hf-* commands into every AI agent on the machine.

Each agent reads skills from its own directory. Rather than copying the tree
into each one -- which guarantees they drift, and a missed copy means an agent
silently runs yesterday's rules -- this links every install back to this repo.
A commit is then a release to all agents at once.

Windows uses directory junctions (no admin needed, unlike symlinks); POSIX uses
symlinks. Existing real directories are never overwritten: the script reports
them and moves on, so a hand-installed copy is your call to remove.

    python scripts/install-global.py            # link everywhere found
    python scripts/install-global.py --dry-run  # show what would happen
    python scripts/install-global.py --list     # just show discovered agents
"""
import argparse
import re
import os
import platform
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
COMMANDS = REPO / "commands"

#: Agents that load skills as DIRECTORIES (one folder per skill, each with a
#: SKILL.md). These get junctions/symlinks straight to the repo.
AGENT_SKILL_DIRS = [
    ".agents/skills",
    ".claude/skills",
    ".codex/skills",
    ".cursor/skills",
    ".hermes/skills",
    ".gemini/antigravity-ide/skills",
    ".gemini/antigravity-backup/skills",
]

#: Agents that load capabilities as FLAT .md FILES, so a directory link cannot
#: reach them. Each entry is (relative dir, flavour).
#:
#:   opencode -> ~/.config/opencode/command/<name>.md becomes /<name>.
#:               Its frontmatter needs `description:`, which our SKILL.md
#:               already has, so we HARD LINK the real file: same inode, so an
#:               edit in the repo is live instantly with zero drift.
#:
#:   zcode    -> ~/.zcode/agents/<name>.md is a subagent persona and needs
#:               `mode: subagent`, which SKILL.md does not carry. A hard link is
#:               therefore impossible, and a content copy would drift. Instead we
#:               generate a THIN POINTER that tells the agent to read the skill
#:               from this repo -- nothing is duplicated, so nothing can go stale.
AGENT_FLAT_FILE_DIRS = [
    (".config/opencode/command", "opencode"),
    (".zcode/agents", "zcode"),
]

ZCODE_POINTER = """---
name: {title}
description: {description}
mode: subagent
---

# {title}

This is a pointer, not a copy. The skill itself lives in one place so it can
never drift out of sync:

**`{skill_path}`**

Read that file in full before acting, along with any `_shared/*.md` it
references from `{shared_path}`.

Generated by `scripts/install-global.py` -- re-run it after changing the skill's
frontmatter. The body is intentionally not duplicated here.
"""

#: The main skill plus every /hf-* command.
def payload():
    items = [("higgsfield-prompt-master", REPO)]
    if COMMANDS.is_dir():
        items += [(d.name, d) for d in sorted(COMMANDS.iterdir())
                  if d.is_dir() and not d.name.startswith("_")]
    return items


def discover(create_missing=False):
    """Skill roots that exist (or that we are willing to create)."""
    home = Path.home()
    found = []
    for rel in AGENT_SKILL_DIRS:
        path = home / rel
        if path.is_dir():
            found.append(path)
        elif create_missing and path.parent.is_dir():
            found.append(path)
    return found


def link(src: Path, dest: Path, dry_run=False) -> str:
    """Point dest at src. Returns a one-word status."""
    if dest.is_symlink() or (os.name == "nt" and dest.is_dir()
                             and _is_junction(dest)):
        if _resolves_to(dest, src):
            return "ok"
        if dry_run:
            return "relink"
        _unlink(dest)
    elif dest.exists():
        # A real directory someone put there by hand. Never clobber it.
        return "skip(real dir)"

    if dry_run:
        return "would-link"

    dest.parent.mkdir(parents=True, exist_ok=True)
    if os.name == "nt":
        # Junctions work without developer mode or admin rights; symlinks do not.
        r = subprocess.run(["cmd", "/c", "mklink", "/J", str(dest), str(src)],
                           capture_output=True, text=True)
        if r.returncode != 0:
            return f"FAILED({r.stderr.strip()[:40]})"
    else:
        dest.symlink_to(src, target_is_directory=True)
    return "linked"


def _frontmatter(skill_md: Path) -> dict:
    """name/description out of a SKILL.md, tolerating YAML block scalars."""
    text = skill_md.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}
    fm, out, key = m.group(1), {}, None
    for line in fm.splitlines():
        head = re.match(r"^(\w+):\s*(.*)$", line)
        if head:
            key = head.group(1)
            val = head.group(2).strip()
            out[key] = "" if val in (">", "|", ">-", "|-") else val
        elif key and line.strip():
            out[key] = (out[key] + " " + line.strip()).strip()
    return out


def install_flat(root: Path, flavour: str, dry_run=False) -> dict:
    """Install every command as a flat .md file for opencode / zcode."""
    stats = {}
    for name, src in payload():
        skill_md = src / "SKILL.md"
        if not skill_md.is_file():
            continue
        dest = root / f"{name}.md"

        if flavour == "opencode":
            # Hard link: one inode, so the repo stays the single source.
            if dest.exists():
                try:
                    if dest.stat().st_ino == skill_md.stat().st_ino:
                        stats["ok"] = stats.get("ok", 0) + 1
                        continue
                except OSError:
                    pass
                if dry_run:
                    stats["would-relink"] = stats.get("would-relink", 0) + 1
                    continue
                dest.unlink()
            if dry_run:
                stats["would-link"] = stats.get("would-link", 0) + 1
                continue
            root.mkdir(parents=True, exist_ok=True)
            try:
                os.link(skill_md, dest)
                stats["hardlinked"] = stats.get("hardlinked", 0) + 1
            except OSError as exc:
                stats[f"FAILED({exc.errno})"] = stats.get(f"FAILED({exc.errno})", 0) + 1

        elif flavour == "zcode":
            fm = _frontmatter(skill_md)
            body = ZCODE_POINTER.format(
                title=fm.get("name", name),
                description=fm.get("description", "").replace("\n", " ").strip(),
                skill_path=skill_md,
                shared_path=COMMANDS / "_shared",
            )
            if dest.exists() and dest.read_text(encoding="utf-8") == body:
                stats["ok"] = stats.get("ok", 0) + 1
                continue
            if dry_run:
                stats["would-write"] = stats.get("would-write", 0) + 1
                continue
            root.mkdir(parents=True, exist_ok=True)
            dest.write_text(body, encoding="utf-8")
            stats["written"] = stats.get("written", 0) + 1
    return stats


def _is_junction(path: Path) -> bool:
    try:
        return bool(os.readlink(str(path)))
    except OSError:
        return False


def _resolves_to(dest: Path, src: Path) -> bool:
    try:
        return dest.resolve() == src.resolve()
    except OSError:
        return False


def _unlink(dest: Path):
    if os.name == "nt" and dest.is_dir():
        subprocess.run(["cmd", "/c", "rmdir", str(dest)], capture_output=True)
    else:
        dest.unlink()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would change, touch nothing")
    ap.add_argument("--list", action="store_true",
                    help="list discovered agent skill directories and exit")
    ap.add_argument("--create-missing", action="store_true",
                    help="also create skill dirs for agents that lack one")
    args = ap.parse_args()

    roots = discover(create_missing=args.create_missing)
    if args.list:
        print(f"{len(roots)} agent skill director(ies):")
        for r in roots:
            print(f"  {r}{'' if r.is_dir() else '  (would be created)'}")
        return 0
    if not roots:
        print("No agent skill directories found.", file=sys.stderr)
        return 1

    items = payload()
    print(f"Linking {len(items)} skill(s) into {len(roots)} agent director(ies) "
          f"on {platform.system()}\n")

    totals = {}
    for root in roots:
        statuses = []
        for name, src in items:
            st = link(src, root / name, dry_run=args.dry_run)
            statuses.append(st)
            totals[st] = totals.get(st, 0) + 1
        summary = ", ".join(f"{v}×{k}" for k, v in
                            sorted({s: statuses.count(s) for s in set(statuses)}.items()))
        print(f"  {str(root):<58} {summary}")

    # Flat-file agents (opencode, zcode) -- a directory link cannot reach these.
    home = Path.home()
    for rel, flavour in AGENT_FLAT_FILE_DIRS:
        root = home / rel
        if not root.is_dir() and not (args.create_missing and root.parent.is_dir()):
            print(f"  {str(root):<58} (not installed, skipped)")
            continue
        stats = install_flat(root, flavour, dry_run=args.dry_run)
        for k, v in stats.items():
            totals[k] = totals.get(k, 0) + v
        summary = ", ".join(f"{v}×{k}" for k, v in sorted(stats.items())) or "nothing"
        print(f"  {str(root):<58} {summary}  [{flavour}]")

    print("\n" + ", ".join(f"{v} {k}" for k, v in sorted(totals.items())))
    if not args.dry_run:
        print(f"\nAll agents now read from {REPO}\nA commit here is a release "
              f"to every agent.")
    failed = sum(v for k, v in totals.items() if k.startswith("FAILED"))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
